/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_ethereum_BREthereumNetwork */

#ifndef _Included_net_people_walletlibcore_ethereum_BREthereumNetwork
#define _Included_net_people_walletlibcore_ethereum_BREthereumNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_people_walletlibcore_ethereum_BREthereumNetwork
 * Method:    jniGetMainnet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_ethereum_BREthereumNetwork_jniGetMainnet
  (JNIEnv *, jclass);

/*
 * Class:     net_people_walletlibcore_ethereum_BREthereumNetwork
 * Method:    jniGetTestnet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_ethereum_BREthereumNetwork_jniGetTestnet
  (JNIEnv *, jclass);

/*
 * Class:     net_people_walletlibcore_ethereum_BREthereumNetwork
 * Method:    jniGetRinkeby
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_ethereum_BREthereumNetwork_jniGetRinkeby
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
