/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_ethereum_BREthereumWallet */

#ifndef _Included_net_people_walletlibcore_ethereum_BREthereumWallet
#define _Included_net_people_walletlibcore_ethereum_BREthereumWallet
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
