/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_BRCoreJniReference */

#ifndef _Included_net_people_walletlibcore_BRCoreJniReference
#define _Included_net_people_walletlibcore_BRCoreJniReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_people_walletlibcore_BRCoreJniReference
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCoreJniReference_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
