/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_BRCoreMasterPubKey */

#ifndef _Included_net_people_walletlibcore_BRCoreMasterPubKey
#define _Included_net_people_walletlibcore_BRCoreMasterPubKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_serialize
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    getPubKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_getPubKey
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    createPubKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_createPubKey
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    createJniCoreMasterPubKeyFromPhrase
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_createJniCoreMasterPubKeyFromPhrase
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    createJniCoreMasterPubKeyFromSerialization
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_createJniCoreMasterPubKeyFromSerialization
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    bip32BitIDKey
 * Signature: ([BILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_bip32BitIDKey
  (JNIEnv *, jclass, jbyteArray, jint, jstring);

/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    validateRecoveryPhrase
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_validateRecoveryPhrase
  (JNIEnv *, jclass, jobjectArray, jstring);

/*
 * Class:     net_people_walletlibcore_BRCoreMasterPubKey
 * Method:    generatePaperKey
 * Signature: ([B[Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCoreMasterPubKey_generatePaperKey
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
