/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_BRCorePaymentProtocolACK */

#ifndef _Included_net_people_walletlibcore_BRCorePaymentProtocolACK
#define _Included_net_people_walletlibcore_BRCorePaymentProtocolACK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    getCustomerMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_getCustomerMemo
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    getMerchantData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_getMerchantData
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    getTransactions
 * Signature: ()[Lcom/breadwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobjectArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_getTransactions
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    getRefundTo
 * Signature: ()[Lcom/breadwallet/core/BRCoreTransactionOutput;
 */
JNIEXPORT jobjectArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_getRefundTo
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    getMerchantMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_getMerchantMemo
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    createPaymentProtocolACK
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_createPaymentProtocolACK
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_serialize
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolACK
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolACK_initializeNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
