/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_BRCoreAddress */

#ifndef _Included_net_people_walletlibcore_BRCoreAddress
#define _Included_net_people_walletlibcore_BRCoreAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    createCoreAddress
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreAddress_createCoreAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    createCoreAddressFromScriptPubKey
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreAddress_createCoreAddressFromScriptPubKey
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    createCoreAddressFromScriptSignature
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreAddress_createCoreAddressFromScriptSignature
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    stringify
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_people_walletlibcore_BRCoreAddress_stringify
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreAddress_isValid
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    getPubKeyScript
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCoreAddress_getPubKeyScript
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    bcashDecodeBitcoin
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_people_walletlibcore_BRCoreAddress_bcashDecodeBitcoin
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_people_walletlibcore_BRCoreAddress
 * Method:    bcashEncodeBitcoin
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_people_walletlibcore_BRCoreAddress_bcashEncodeBitcoin
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
