/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_BRCorePaymentProtocolPaymentACK */

#ifndef _Included_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
#define _Included_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    getCustomerMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_getCustomerMemo
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    getMerchantData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_getMerchantData
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    getTransactions
 * Signature: ()[Lcom/breadwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobjectArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_getTransactions
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    getRefundTo
 * Signature: ()[Lcom/breadwallet/core/BRCoreTransactionOutput;
 */
JNIEXPORT jobjectArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_getRefundTo
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    getMerchantMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_getMerchantMemo
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    createPaymentProtocolPaymentACK
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_createPaymentProtocolPaymentACK
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_serialize
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCorePaymentProtocolPaymentACK
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCorePaymentProtocolPaymentACK_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
