/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_people_walletlibcore_BRCoreWallet */

#ifndef _Included_net_people_walletlibcore_BRCoreWallet
#define _Included_net_people_walletlibcore_BRCoreWallet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    createJniCoreWallet
 * Signature: ([Lcom/breadwallet/core/BRCoreTransaction;Lcom/breadwallet/core/BRCoreMasterPubKey;)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_createJniCoreWallet
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    installListener
 * Signature: (Lcom/breadwallet/core/BRCoreWallet/Listener;)V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCoreWallet_installListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getReceiveAddress
 * Signature: ()Lcom/breadwallet/core/BRCoreAddress;
 */
JNIEXPORT jobject JNICALL Java_net_people_walletlibcore_BRCoreWallet_getReceiveAddress
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getAllAddresses
 * Signature: ()[Lcom/breadwallet/core/BRCoreAddress;
 */
JNIEXPORT jobjectArray JNICALL Java_net_people_walletlibcore_BRCoreWallet_getAllAddresses
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    containsAddress
 * Signature: (Lcom/breadwallet/core/BRCoreAddress;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_containsAddress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    addressIsUsed
 * Signature: (Lcom/breadwallet/core/BRCoreAddress;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_addressIsUsed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    jniGetTransactions
 * Signature: ()[Lcom/breadwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobjectArray JNICALL Java_net_people_walletlibcore_BRCoreWallet_jniGetTransactions
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getTransactionsConfirmedBefore
 * Signature: (J)[Lcom/breadwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobjectArray JNICALL Java_net_people_walletlibcore_BRCoreWallet_getTransactionsConfirmedBefore
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getBalance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getBalance
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getTotalSent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getTotalSent
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getTotalReceived
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getTotalReceived
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getFeePerKb
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getFeePerKb
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    setFeePerKb
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCoreWallet_setFeePerKb
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getMaxFeePerKb
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getMaxFeePerKb
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getDefaultFeePerKb
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getDefaultFeePerKb
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    createTransaction
 * Signature: (JLcom/breadwallet/core/BRCoreAddress;)Lcom/breadwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobject JNICALL Java_net_people_walletlibcore_BRCoreWallet_createTransaction
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    createTransactionForOutputs
 * Signature: ([Lcom/breadwallet/core/BRCoreTransactionOutput;)Lcom/breadwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobject JNICALL Java_net_people_walletlibcore_BRCoreWallet_createTransactionForOutputs
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    signTransaction
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_signTransaction
  (JNIEnv *, jobject, jobject, jint, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    containsTransaction
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_containsTransaction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    jniRegisterTransaction
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_jniRegisterTransaction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    removeTransaction
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCoreWallet_removeTransaction
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    updateTransactions
 * Signature: ([[BJJ)V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCoreWallet_updateTransactions
  (JNIEnv *, jobject, jobjectArray, jlong, jlong);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    jniTransactionForHash
 * Signature: ([B)Lcom/breadwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobject JNICALL Java_net_people_walletlibcore_BRCoreWallet_jniTransactionForHash
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    transactionIsValid
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_transactionIsValid
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    transactionIsPending
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_transactionIsPending
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    transactionIsVerified
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_people_walletlibcore_BRCoreWallet_transactionIsVerified
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getTransactionFee
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getTransactionFee
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getTransactionAmountSent
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getTransactionAmountSent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getTransactionAmountReceived
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getTransactionAmountReceived
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getBalanceAfterTransaction
 * Signature: (Lcom/breadwallet/core/BRCoreTransaction;)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getBalanceAfterTransaction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getFeeForTransactionSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getFeeForTransactionSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getFeeForTransactionAmount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getFeeForTransactionAmount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getMinOutputAmount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getMinOutputAmount
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    getMaxOutputAmount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_people_walletlibcore_BRCoreWallet_getMaxOutputAmount
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCoreWallet_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     net_people_walletlibcore_BRCoreWallet
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_people_walletlibcore_BRCoreWallet_initializeNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
